project:
  output-dir: ./docs/de

website:
  title: "Data Science"
  site-url: "https://www.swtdata.org/"
  description: "Tools and software developed at Swisstransplant."
  search: false
  favicon: images/SWT_icon_kreis_blau_2020_196x196.png
  navbar:
    logo: "images/SWT_icon_cmyk2020.png"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Statistiken"
        href: posts.qmd
      - text: "Forschung"
        menu:
        - tools/index.qmd
        - text: "KIDMO"
          href: kidmo/index.qmd
        - text: "EXAM"
          href: https://swisstransplant.shinyapps.io/EXAM/
          icon: "box-arrow-up-right"
          target: _blank
      #- text: Publications
      #  href: publications/index.qmd
      - text: About
        href: about/index.qmd
      - icon: github
        href: https://github.com/Swisstransplant
    right:
      - text: Deutsch
        href: ../de
      - text: English
        href: ../en
        
  page-footer:
    left: 'Â© 2023, 2024 Swisstransplant'

lang: de

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
