project:
  type: website
  output-dir: ./docs/fr

website:
  title: "Swisstransplant Data"
  site-url: "https://data.swisstransplant.org/"
  description: "Plateforme en ligne proposant des statistiques actuelles et des outils d'analyse dans le domaine du don d'organes et de la transplantation."
  search: false
  open-graph: true
  favicon: images/SWT_icon_kreis_blau_2020_196x196.png
  navbar:
    title: false
    logo: "images/SWT_2955_2021.png"
    logo-alt: "Logo Swisstransplant"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Rapports statistiques"
        href: posts.qmd
      - text: "Recherche"
        menu:
        - text: "EXAM"
          href: exam/index.qmd
        - text: "KIDMO"
          href: kidmo/index.qmd
        - text: "Publications"
          href: publications/index.qmd
        - tools/index.qmd
      - text: "Qui sommes-nous?"
        href: about/index.qmd
    right:
      - text: "DE"
        href: ..
        
  page-footer:
    left: 'Â© 2023--2026 Swisstransplant'
  google-analytics:
    tracking-id: "G-NJH1JBVDQV"
    anonymize-ip: true

lang: fr

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    link-external-icon: true
    link-external-newwindow: true
